apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: "10.10.100.80"
  bindPort: 6443
nodeRegistration:
  criSocket: unix:///run/containerd/containerd.sock

---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: v1.28.15
networking:
  podSubnet: "10.244.0.0/16"
etcd:
  local:
    dataDir: /media/de/k8s/etcd

